config/routes.rb
Rails.application.routes.draw do
  resource :wechat, only: [:show, :create] do
    collection do
      get :message_box
      get :direct_message_box
    end
  end

  root to: 'visitors#works'
  get '/index'=>'visitors#index'
  get '/admin'=>'users#index'
  get '/ranking'=>'visitors#ranking'
  get '/review'=>'visitors#review'
  get '/intro'=>'visitors#intro'
  get '/works'=>'visitors#works'
  get '/my_account'=>'visitors#my_account'
  get '/subscribe'=>'visitors#subscribe'
  get '/show/:id'=>'visitors#show'

  devise_for :users

  resources :users

  resources :shops
  resources :cards
  resources :activities do
    resources :photographs do
      collection do
        get :search
      end
      member do
        get :vote
        get :user_edit
        patch :user_update
      end
    end
    #resources :coupons do
    #  collection do
    #    get :search
    #  end
    #end
  end
  namespace :api do
    namespace :v1 do
      resource :wechat, only: [:show, :create]
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  layout "wechat"
  before_action :set_wechat_user, except: [:subscribe]

  def index
  end

  def works
    @order_by = params[:order] ? params[:order] : "created_at"
    @current_page = params[:page] ? params[:page].to_i : 1
    @photographs = @activity.photographs.order("#{@order_by} desc").paginate(:page => params[:page])
  end

  def review
    @card = Card.first
  end

  def subscribe
    render :subscribe, layout: 'subscribe'
  end

  def my_account
    @photograph = @activity.photographs.select{|p|p.user_id==@current_wechat_user.id}.first
    @card = Card.first
  end

  def show
    @photograph = Photograph.find(params[:id])
  end

  def ranking
    @photographs = @activity.photographs.order("vote_numbers desc")#.paginate(:page => params[:page])
  end

  def intro
  end

  private


end

app/views/visitors/_intro.html.erb
<article class="weui-article">
  <section>
    <p><%=raw @activity.intro%></p>
  </section>
</article>

app/views/visitors/_ranking.html.erb
<div class="weui-panel weui-panel_access">
  <div class="weui-panel__bd">
    <%page = params[:page].present? ? params[:page].to_i : 1%>
    <%rank = (page-1) * Photograph.per_page + 1%>
    <table style="width:100%;" cellpadding="0" cellspacing="0">
      <tr style="background-color: #F8B62D;color: #40220F;">
        <td class="ranking_table">排行</td>
        <td class="ranking_table">名称</td>
        <td class="ranking_table">票数</td>
      </tr>
    <%@photographs.each do |photograph|%>
      <tr>
        <td class="ranking_table"><b><%= rank%></b></td>
        <td class="ranking_table"><b><%= photograph.name%></b></td>
        <td class="ranking_table"><b><%= photograph.vote_numbers.to_i%></b></td>
      </tr>
      <%rank +=1%>
    <%end%>
    </table>
  </div>

</div>

app/views/visitors/_show.html.erb
<article class="weui-article" style="padding:5px;">
  <section>
    <% @photograph.photos.each do |photo|%>
      <div class="photo_item" <% if photo.id != @photograph.photos.first.id%>style="display:none;"<%end%>>
        <%= image_tag photo.photo.url(:big), id:"my_photo"%>
      </div>
    <%end%>
  </section>

      <%= link_to vote_activity_photograph_path(@activity,@photograph), remote:true do%>
        <div align="center" style="width:50%;background-color:#F8B62D;color:white;padding:10px 0;float:left;">
          <%=fa_icon "heart-o", text:"投票", style:"color:white;"%>
        </div>
      <%end%>
      <div id="share_time_line" align="center" style="width:50%;background-color:#40220F;color:white;padding:10px 0;float:left;">
        <%=fa_icon "thumbs-o-up", text:"为TA加油", style:"color:white;"%>
      </div>

  <section>
      <div class="weui-media-box__bd" style="padding:20px;">
        <%avatar_url = @photograph.user.avatar.present? ? @photograph.user.avatar : ""%>
        <%=image_tag avatar_url, width:80, height:80, align:"right", style:"border-radius:50%;margin-top:15px;" %>
        <%=fa_icon "heart-o", style:"color:#F8B62D;"%>
        <span id="votes<%= @photograph.id%>"><%=@photograph.vote_numbers.to_i%></span>
        <h1>#<%=@photograph.name%></h1>
        <h2 style="color:gray;"><%=@photograph.intro%></h2>
      </div>
  </section>
</article>

<script>
  $(function(){
    $("#share_time_line").on('click', function(){
      alert("点击页面右上角“...”。邀请好友助力，晒萌娃，PO萌餐，丰厚奖品等你拿！");
      //WeixinJSBridge.invoke('shareTimeline');
    });

    <% if flash[:notice].present? && flash[:notice] == "create photograph" %>
      $(".weui-dialog__bd").html("上传成功，您获得了一张<%=Card.first.name%>，请到我的优惠券查看！")
      $('#iosDialog2').fadeIn(200);
    <%end%>
  });
</script>

app/views/visitors/_work_item.html.erb
<%@photographs.to_a.each_index do |index|%>
  <%photograph = @photographs[index]%>
  <%if (index%2)==i%>
    <article class="weui-article page<%=page%>" style="padding:5px;">
      <section>
        <%=link_to "/show/#{photograph.id}", remote:true do %>
          <%=image_tag photograph.cover_url(:medium) %>
        <%end%>
      </section>
      <section>
          <div class="weui-media-box__bd" style="padding:20px;">
            <%avatar_url = photograph.user.avatar.present? ? photograph.user.avatar : ""%>
            <%=image_tag avatar_url, width:30, height:30, align:"right", style:"border-radius:50%;" %>
            <%=link_to vote_activity_photograph_path(@activity,photograph), remote:true do%>
              <%=fa_icon "heart-o", style:"color:#F8B62D;"%>
            <%end%>
            <span id="votes<%= photograph.id%>"><%=photograph.vote_numbers.to_i%></span>
            <h1>#<%=photograph.name%></h1>
            <%if photograph.intro.present?%>
              <h2 style="color:gray;"><%=photograph.intro[0,20]%>...</h2>
            <%end%>
        </div>
      </section>
    </article>
  <%end%>
<%end%>

app/views/visitors/_works.html.erb
<div style="display:flex;justify-content:space-around;width:100%;float:left;margin:20px 0;">
  <%nclass = @order_by == "created_at" ? "tab_menu_selected" : "tab_menu"%>
  <%=link_to "最新", "/works", :remote=>true, class:nclass %>
  <%hclass = @order_by == "vote_numbers" ? "tab_menu_selected" : "tab_menu"%>
  <%=link_to "最热", "/works?order=vote_numbers", :remote=>true, class:hclass %>
</div>

<div class="wcpc_content">
  <%2.times do |i|%>
    <div id="works<%=i+1%>" style="width:50%;float:left;">
      <%=render :partial=>"work_item", locals:{i: i, page:@current_page.to_s}%>
    </div>
  <%end%>
  <div id="refresh_outer" style="float:left;width:100%;text-align:center;">
    下面还有哦
    <%=link_to "点击刷新", "/works?order=#{@order_by}&page=#{(@current_page+1).to_s}", :remote=>true, :id=>"refresh", style:"color:gray;display:none;" %>
  </div>

</div>

app/views/visitors/_works_top.html.erb
  <div id="worktop_swiper" class="swiper-container" style="width:100%;">
    <div class="swiper-wrapper">
        <div class="photo_item swiper-slide">
          <%=image_tag "workstop1.jpg", id:"poster1", style:"width:100%;"%>
        </div>
        <div class="photo_item swiper-slide">
          <%=image_tag "workstop2.jpg", id:"poster2", style:"width:100%;" %>
        </div>
    </div>
  </div>
  <script>
    $(function(){
      var img_height=$("#poster1").height();
      $("#worktop_swiper").height(img_height);
    });
  </script>

app/views/visitors/index.html.erb
<article class="weui-article main">
  <div class="swiper-container" >
    <section class="swiper-wrapper">

        <p class="photo_item swiper-slide">
          <%=link_to "/review" do %>
            <%=image_tag "poster1.jpg", id:"poster2" %>
          <%end%>
        </p>
        <p class="photo_item swiper-slide">
          <%=link_to new_activity_photograph_path(@activity), remote:true do %>
            <%=image_tag "poster2.jpg", id:"poster3" %>
          <%end%>
        </p>
    </section>


    <div class="swiper-pagination"></div>
  </div>
</article>

app/views/visitors/intro.js.erb
custom_popup({
  title: "活动介绍",
  text: <%== ( render :partial => 'intro',:formats=>[:html] ).to_json %>,
  buttons: [{ text: "关闭", onClick: function(){ $.closeModal();} } ]
});

app/views/visitors/my_account.html.erb
<%avatar_url = @current_wechat_user.avatar.present? ? @current_wechat_user.avatar : ""%>
<div id="cover" style="width:100%;background-image:url(<%=image_url 'cover.jpg'%>);background-repeat: no-repeat;background-size:100%;">
  <table id="cover_table" style="width:100%;padding-top:450px;">
    <tr>
      <td align="center">
        <div style="width:80px;height:80px;padding:10px;background-color:white;" class="round">
          <%=image_tag avatar_url, width:80, height:80, align:"right", class:"round" %>
        </div>
      </td>
    </tr>
  </table>
</div>
  <center style="margin-top:60px;"><span style="margin:30px;"><%=@current_wechat_user.nickname%></span></center>
  <div style="width:50%;float:left;margin-top:20px;">
    <div id="my_work" style="border-bottom:solid 2px black;padding:5px;text-align:center;">
      我的作品
    </div>
  </div>
  <div style="width:50%;float:left;margin-top:20px;">
    <div id="my_card" style="border-bottom:solid 1px black;padding:5px;text-align:center;">
      我的卡券
    </div>
  </div>
  <div id="works" style="width:100%;float:left;">
    <%if @photograph.present? %>
      <% @photograph.photos.each do |photo|%>
        <article class="weui-article" style="padding:5px;">
          <section>
            <%= image_tag photo.photo.url%>
          </section>
          <div class="weui-btn-area">
            <%=link_to "修改作品", user_edit_activity_photograph_path(@activity, @photograph), remote:true, class:"weui-btn weui-btn_primary", style:"color:#40220F;"%>
          </div>
        </article>
      <%end%>
    <%else%>
      暂无作品
    <%end%>
  </div>
  <div id="cards" style="width:100%;float:left;display:none;">
    <%if (@current_wechat_user.votes.present? || @photograph.present?) && @card.present? %>
      <div style="width:100%;background-color:#e8e8e8;display:none;">
        <div style="width:100%;background-color:#016934;color:#f5d09d;height:150px;float:left;">
          <div style="width:100%;text-align:center;margin:20px 0;"><span style="font-weight:bold;font-size:2em;"><%=@card.name%></span></div>
          <div style="width:100%;text-align:center"><span><%=@card.duration%></span></div>
        </div>
        <div style="width:100%;height:35px;background-image:url(<%=image_url 'wave.jpg'%>);background-repeat: repeat-x;float:left;">
          &nbsp;
        </div>
        <div style="width:100%;background-color:white;color:gray;height:80px;float:left;margin-bottom:10px;">
          <span><%=@card.origin%></span>
        </div>
        <div class="weui-btn-area">
          <%=link_to "进入商城", @card.outer_url, class:"weui-btn weui-btn_primary", style:"color:#40220F;"%>
        </div>
      </div>
    <%else%>
      暂无卡券
    <%end%>
  </div>

app/views/visitors/ranking.html.erb
<div class="weui-panel weui-panel_access">
  <div class="weui-panel__hd">投票排名（票数多者在前）</div>
  <div class="weui-panel__bd">
    <%page = params[:page].present? ? params[:page].to_i : 1%>
    <%rank = (page-1) * Photograph.per_page + 1%>
    <%@photographs.each do |photograph|%>
      <%=link_to "/show/#{photograph.id}", class:"weui-media-box weui-media-box_appmsg" do %>
        <div class="weui-media-box__hd">
          <%=image_tag photograph.cover_url(:thumb), width:"60", height:"60" %>
        </div>
        <div class="weui-media-box__bd">
          <h4 class="weui-media-box__title"><b><%= rank%></b><%= photograph.name%></h4>
          <p class="weui-media-box__desc"><span>票数：<%=photograph.vote_numbers.to_i%></span></p>
        </div>
      <%end%>
      <%rank +=1%>
    <%end%>
  </div>
  <div class="weui-panel__ft">
    <%= will_paginate @photographs %>
  </div>
</div>

app/views/visitors/ranking.js.erb
custom_popup({
  title: "投票排名",
  text: <%== ( render :partial => 'ranking',:formats=>[:html] ).to_json %>,
  buttons: [{ text: "关闭", onClick: function(){ $.closeModal();} } ]
});

app/views/visitors/show.html.erb
<article class="weui-article" style="padding:5px;">
  <img src="" class="wx-share">
  <section>
    <% @photograph.photos.each do |photo|%>
      <div class="photo_item" <% if photo.id != @photograph.photos.first.id%>style="display:none;"<%end%>>
        <%= image_tag photo.photo.url%>
      </div>
    <%end%>
  </section>

      <%= link_to vote_activity_photograph_path(@activity,@photograph), remote:true do%>
        <div align="center" style="width:50%;background-color:#F8B62D;color:white;padding:10px 0;float:left;">
          <%=fa_icon "heart-o", text:"投票", style:"color:white;"%>
        </div>
      <%end%>
      <div id="share_time_line" align="center" style="width:50%;background-color:#40220F;color:white;padding:10px 0;float:left;">
        <%=fa_icon "thumbs-o-up", text:"为TA加油", style:"color:white;"%>
      </div>

  <section>
      <div class="weui-media-box__bd" style="padding:20px;">
        <%avatar_url = @photograph.user.avatar.present? ? @photograph.user.avatar : ""%>
        <%=image_tag avatar_url, width:80, height:80, align:"right", style:"border-radius:50%;" %>
        <%=fa_icon "heart-o", style:"color:#F8B62D;"%>
        <span id="votes<%= @photograph.id%>"><%=@photograph.vote_numbers.to_i%></span>
        <h1>#<%=@photograph.name%></h1>
        <h2 style="color:gray;"><%=@photograph.intro%></h2>
      </div>
  </section>
</article>

<script>
  $(function(){
    $("#share_time_line").on('click', function(){
      alert("点击 页面右上角“...”，邀请好友助力，晒萌娃，PO萌餐，丰厚奖品等你拿！");
      WeixinJSBridge.invoke('shareTimeline');
    });

    <% if flash[:notice].present? && flash[:notice] == "create photograph" %>
      $(".weui-dialog__bd").html("上传成功，您获得了一张<%=Card.first.name%>，请到我的优惠券查看！")
      $('#iosDialog2').fadeIn(200);
    <%end%>
  });
</script>

app/views/visitors/show.js.erb
window.share_config.share.imgUrl = <%== @photograph.photos[0].photo.url(:medium).to_json%>;
window.share_config.share.link = <%==url_for( action: :show, id: @photograph.id, only_path: false).to_json %>;

custom_popup({
  title: "<%@photograph.user.nickname%>的作品",
  text: <%== ( render :partial => 'show',:formats=>[:html] ).to_json %>,
  buttons: [{ text: "关闭", onClick: function(){ $.closeModal();} } ]
});

app/views/visitors/subscribe.html.erb
<article class="weui-article main">

<%= image_tag "qrcode.jpg" %>

</article>