config/routes.rb
Rails.application.routes.draw do
  resource :wechat, only: [:show, :create] do
    collection do
      get :message_box
      get :direct_message_box
    end
  end

  root to: 'visitors#works'
  get '/index'=>'visitors#index'
  get '/admin'=>'users#index'
  get '/ranking'=>'visitors#ranking'
  get '/review'=>'visitors#review'
  get '/intro'=>'visitors#intro'
  get '/works'=>'visitors#works'
  get '/my_account'=>'visitors#my_account'
  get '/subscribe'=>'visitors#subscribe'
  get '/show/:id'=>'visitors#show'

  devise_for :users

  resources :users

  resources :shops
  resources :cards
  resources :activities do
    resources :photographs do
      collection do
        get :search
      end
      member do
        get :vote
        get :user_edit
        patch :user_update
      end
    end
    #resources :coupons do
    #  collection do
    #    get :search
    #  end
    #end
  end
  namespace :api do
    namespace :v1 do
      resource :wechat, only: [:show, :create]
    end
  end
end

app/models/photograph.rb
class Photograph < ApplicationRecord
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/pic_160.png"
  include PaperclipAliyunOssHelper

  belongs_to :activity
  belongs_to :user
  has_many :votes, dependent: :destroy
  has_many :photos, dependent: :destroy
  validates_attachment :photo, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  accepts_nested_attributes_for :photos, allow_destroy: true
  accepts_nested_attributes_for :user, allow_destroy: false

  validates :photos, presence: true
  validates :name, length: { in: 2..15 }
  validates :intro, length: { in: 2..60 }, if: Proc.new {|p|p.intro.present?}

  after_create :get_card

  cattr_accessor :upload_limit



  self.per_page = 6
  self.upload_limit = 1

  def cover_url(psize=nil)
    return photos.first.photo.url(psize)
    #photo ? photo.url(psize) : photos.first.photo.url(psize)
  end

  def vote(wechat_user_id)
    vote = self.votes.create(user_id:wechat_user_id)
    if vote && vote.errors.blank?
      self.vote_numbers = self.vote_numbers.to_i+1
      self.save
    end
    return vote
  end

  def get_card
    wx_user = self.user
    wx_user.card_status = 1
    wx_user.save
    #coupon = Coupon.where(user_id: nil).first
    #if coupon.present?
    #  coupon.user_id=user_id
    #  coupon.save
    #end
  end
end

app/controllers/photographs_controller.rb
class PhotographsController < ApplicationController
  layout "wechat", only: [:new, :create, :vote]
  before_action :set_wechat_user, only: [:new, :create, :vote, :user_edit, :user_update]
  before_action :authenticate_user!, except: [:new, :create, :vote, :user_edit, :user_update]
  before_action :set_photograph, only: [:show, :edit, :update, :user_edit, :user_update, :destroy, :vote]

  after_action :set_user_subscribed, only: [:new ]

  def index
    order = params[:order] ? params[:order] : "created_at desc"
    @photographs = @activity.photographs.order(order).paginate(:page => params[:page])
  end

  def search
    if params[:name].present?
      @photographs=@activity.photographs.where("name=?",params[:name]).paginate(:page => params[:page])
    else
      @photographs = @activity.photographs.paginate(:page => params[:page])
    end
    render :index
  end

  def new
    #@photograph = @activity.photographs.build(user_id:@current_wechat_user.id)
    @photograph =  @activity.photographs.find_or_initialize_by(user_id:@current_wechat_user.id)

    if @photograph.persisted?
    #  redirect_to "/show/#{@photograph.id}"
    else
      Photograph.upload_limit.times { @photograph.photos.build}
    end
    Rails.logger.debug "@photograph=#{@photograph.errors.inspect}"
  end

  def create
    @photograph = Photograph.create(photograph_params)
    if params["photograph"]["user_attributes"]
      @current_wechat_user.phone=params["photograph"]["user_attributes"]["name"]
      @current_wechat_user.phone=params["photograph"]["user_attributes"]["phone"]
      @current_wechat_user.save
    end
    if @photograph.errors.empty?
      redirect_to "/show/#{@photograph.id}"
    else
      logger.debug "++++++++++++++++++++++++++@photograph.errors=#{@photograph.errors.inspect}"
      (Photograph.upload_limit-@photograph.photos.size).times { @photograph.photos.build}
      render :new
    end

  end

  def show
  end

  def edit
    (Photograph.upload_limit-@photograph.photos.size).times { @photograph.photos.build}
  end

  def update
    @photograph.update(photograph_params)
    if @photograph.errors.empty?
      flash[:notice] = "作品修改成功"
      redirect_to activity_photograph_path(@activity,@photograph)
    else
      logger.debug "++++++++++++++++++++++++++@photograph.errors=#{@photograph.errors.inspect}"
      (Photograph.upload_limit-@photograph.photos.size).times { @photograph.photos.build}
      render :edit
    end
  end

  def user_edit
    (Photograph.upload_limit-@photograph.photos.size).times { @photograph.photos.build}
  end

  def user_update
    permitted_params = photograph_params
    @photograph.update(permitted_params)
    if params["photograph"]["user_attributes"]
      @current_wechat_user.phone=params["photograph"]["user_attributes"]["name"]
      @current_wechat_user.phone=params["photograph"]["user_attributes"]["phone"]
      @current_wechat_user.save
    end
    # if params["photograph"]["photos_attributes"].present?
    #   photo_params = params["photograph"]["photos_attributes"]['0']
    #   Rails.logger.debug  photo_params.inspect
    #   photo = Photo.find( photo_params['id'].to_i )
    #   photo.update( photo_params )
    # end

    if @photograph.errors.empty?
      respond_to do |format|
        format.html { redirect_to "/show/#{@photograph.id}" }
        format.js { render :user_update }
      end
    else
      logger.debug "++++++++++++++++++++++++++@photograph.errors=#{@photograph.errors.inspect}"
      (Photograph.upload_limit-@photograph.photos.size).times { @photograph.photos.build}
      render :user_edit
    end
  end

  def destroy
    @photograph.destroy
    redirect_to activity_photographs_path(@activity)
  end

  def vote
    @vote = @photograph.vote(@current_wechat_user.id)
  end

  private

  def photograph_params
    params.require(:photograph).permit( :user_id, :activity_id, :name, :vote_numbers, :intro, photos_attributes: [:id,:base64_image,:photo,:_destroy], user_attributes: [:id,:name,:photo] )
  end

  def set_photograph
    @photograph = Photograph.find(params[:id])
  end

  def set_user_subscribed
    @current_wechat_user.update_attribute(:subscribed, true)
  end
end

app/helpers/photographs_helper.rb
module PhotographsHelper
end

app/views/photographs/_new.html.erb
<% if !@current_wechat_user.subscribed %>
<div style="width:100%;">
  <%=image_tag "qrcode.jpg", style:"width:100%;" %>
</div>
<% else %>
<div id="cover" style="width:100%;">
  <%=image_tag "cover.jpg", style:"width:100%;" %>
</div>
<center>
  <%=link_to nil, href:"#", onclick:"$('#photograph_photos_attributes_0_photo').click();" do %>
    <div style="background-color:#F8B62D;color:#40220F;margin:15px 0;padding:10px 0;width:90%;text-align:center;">
      <h4>上传图片</h4>
    </div>
  <% end %>
<div style="width:90%;">
  <%form_action =@photograph.persisted? ? "user_update" : "create"%>
  <%= form_for(@photograph, url: {:action=>form_action}, remote:true, html: {class: 'photograph_form'}  ) do |f| %>
    <div style="color:#F8B62D;font-size:0.7em;">标*为必填项</div>
    <div class="weui-cell <%if @photograph.errors.include?(:photos)%>weui-cell_warn<%end%>">
      <div class="weui-cell__hd">
        <div style="float:left;padding-right:10px;">*</div>
        <%= f.label :photo, class:"weui-label", style:"text-align:left;float:left;" %>
      </div>
    </div>
    <div class="weui-cell <%if @photograph.errors.include?(:photos)%>weui-cell_warn<%end%>">
      <div id="photos_div" class="weui-cell__bd">
        <%= f.fields_for :photos do |photos_form| %>
          <div id="wrapper_div<%=photos_form.index%>" class="wrapper_div">
            <div id="photodiv<%=photos_form.index%>" class="weui-uploader__file" style="display:none;">
              <%=link_to nil, href:"#", onclick:"delete_photo(#{photos_form.index});" do %>
                <i class="weui-icon-cancel" style="margin-left: 50px;"></i>
              <% end %>
              <div style="margin-top:-25px;float:left;">
                <%=image_tag "pic_160.png", id:"photo#{photos_form.index}", width:"80", height:"80"%>
              </div>
            </div>
            <div id="uploaddiv<%=photos_form.index%>" class="weui-uploader__input-box" <% if photos_form.index > 0 %> style="display:none;"<%end%>>
              <%= photos_form.file_field :photo, class:"weui-uploader__input", onchange:"preview_photo(this,#{photos_form.index})" %>
            </div>
          </div>
          <%= photos_form.hidden_field :base64_image, class: 'base64_image' %>

        <% end %>
        <%if @photograph.errors.include?(:photos)%>请上传一张图片，格式为jpg, jpeg, png或gif<%end%>
      </div>
    </div>
    <div class="weui-cells__tips" style="text-align:left;">温馨提示：</br>建议您上传的萌宝照片尺寸不要超过8M，否则可能读取不到照片的参数而造成不能成功上传。</div>

    <div class="weui-cells weui-cells_form">
      <div class="weui-cell <%if @photograph.errors.include?(:name)%>weui-cell_warn<%end%>">
        <div class="weui-cell__hd">
          <div style="float:left;padding-right:10px;">*</div>
          <%= f.label :name, class:"weui-label", style:"text-align:left;" %>
        </div>
      </div>
      <div class="weui-cell <%if @photograph.errors.include?(:name)%>weui-cell_warn<%end%>">
        <div class="weui-cell__bd">
          <%name_ph = @photograph.errors.size > 0 ? @photograph.errors.messages[:name][0] : "限15字符"%>
          <%= f.text_field :name, class:"weui-input", placeholder: name_ph, required: true%>
        </div>
      </div>
      <div id="name_rest" class="weui-cells__tips" style="text-align:left;">（剩余15字符）</div>
      <div class="weui-cell <%if @photograph.errors.include?(:intro)%>weui-cell_warn<%end%>">
        <div class="weui-cell__hd">
          <%= f.label :intro, class:"weui-label", style:"text-align:left;" %>
        </div>
      </div>
      <div class="weui-cell <%if @photograph.errors.include?(:intro)%>weui-cell_warn<%end%>">
        <div class="weui-cell__bd">
          <%intro_ph = @photograph.errors.size > 0 ? @photograph.errors.messages[:intro][0] : "限60字符"%>
          <%= f.text_area :intro, class:"weui-textarea", placeholder:intro_ph, rows:"5" %>
        </div>
      </div>
      <div id="intro_rest" class="weui-cells__tips" style="text-align:left;">（剩余60字符）</div>
      <%= f.fields_for :user do |user_form| %>
        <div class="weui-cell">
          <div class="weui-cell__hd">
            <div style="float:left;padding-right:10px;">*</div>
            <%= user_form.label :name, class:"weui-label", style:"text-align:left;" %>
          </div>
        </div>
        <div class="weui-cell">
          <div id="user_div" class="weui-cell__bd">
            <div class="weui-cell__bd">
              <%= user_form.text_field :name, class:"weui-input", placeholder:"请输入姓名", required: true%>
            </div>
          </div>
        </div>

        <div class="weui-cell">
          <div class="weui-cell__hd">
            <div style="float:left;padding-right:10px;">*</div>
            <%= user_form.label :phone, class:"weui-label", style:"text-align:left;" %>
          </div>
        </div>
        <div class="weui-cell">
          <div id="user_div" class="weui-cell__bd">
            <div class="weui-cell__bd">
              <%= user_form.text_field :phone, class:"weui-input", type:"tel", placeholder:"请输入手机号", required: true%>
            </div>
          </div>
        </div>
        <div id="intro_rest" class="weui-cells__tips" style="text-align:left;font-size:0.7em;">填写姓名和电话便于后期获奖通知</div>
      <% end %>
      <%= f.hidden_field :user_id %>
      <%= f.hidden_field :activity_id %>

      <div class="weui-btn-area">
        <%= f.submit "确定发布", class:"weui-btn weui-btn_primary", id: 'submitPhotoBtn' %>
      </div>
      <p>&nbsp;</p>
    </div>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
  <% end %>
</div>
</center>
<% end %>
<script>
$(document).ready(function(){
  $("#photograph_name").on('change', function(){
    refresh_rest("photograph_name", "name_rest", 15)
  });

  $("#photograph_intro").on('change', function(){
    refresh_rest("photograph_intro", "intro_rest", 60)
  });
  // 手机号码验证
  jQuery.validator.addMethod("isMobile", function(value, element) {
  var length = value.length;
  var mobile = /^(13[0-9]{9})|(18[0-9]{9})|(14[0-9]{9})|(17[0-9]{9})|(15[0-9]{9})$/;
  return this.optional(element) || (length == 11 && mobile.test(value));
  }, "请正确填写您的手机号码");

  $("#new_photograph").validate({
      rules:{
        'photograph[name]':{
          required: true,
          rangelength:[2,15]
        },
        'photograph[intro]':{
          required: false,
          rangelength:[2,60]
        },
        'photograph[user_attributes][name]':{
            required:true,
        },
        'photograph[user_attributes][phone]':{
            required:true,
            isMobile: true
        }
      },
      messages : {
        'photograph[name]' : {
            required : "作品名称别忘了填",
            rangelength : "名称需要2-15位字符"
        },
        'photograph[intro]':{
          rangelength:"介绍文字需要2-60位字符"
        },
        'photograph[user_attributes][name]':{
            required:"请留下您的姓名哦",
        },
        'photograph[user_attributes][phone]' : {
            required : "需要您的联系方式哦",
            minlength : "电话号码需要11位哦"
        }
      }

    })
})
</script>

app/views/photographs/_records.html.erb
  <table class="table table-striped">
    <thead>
      <tr>
        <th>作品名称</th>
        <th>作者</th>
        <th>票数</th>
        <th colspan="3">
          <%=link_to "查看排名", activity_photographs_path(@activity, order: "vote_numbers desc")%>
        </th>
      </tr>
    </thead>

    <tbody>
      <% if @photographs.empty? %>
        <tr>
          <td colspan="6">暂无作品</td>
        <tr>
      <% else %>
      <% @photographs.each do |photograph| %>
        <tr>
          <td><%= photograph.name %></td>
          <td><%=link_to (photograph.user.try :nickname), user_path(photograph.user.id) %></td>
          <td><%= photograph.try :vote_numbers %></td>
          <td><%= link_to "查看", activity_photograph_path(@activity, photograph), method: 'get' %></td>
          <td><%= link_to "编辑", edit_activity_photograph_path(@activity, photograph) %></td>
          <td><%= link_to "删除", activity_photograph_path(@activity, photograph), method: 'delete' %></td>
        </tr>
      <% end %>
    <% end %>

    </tbody>
  </table>

<%= will_paginate @photographs if @photographs.respond_to? :total_pages%>

app/views/photographs/edit.html.erb
<div> <h2 class="page-header">编辑作品 </h2>
</div>
<div>
  <%= simple_form_for(@photograph, url: {:action=>"update"} ) do |f| %>
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :intro %>
      <%= f.input :vote_numbers %>
      <%= f.input :manifesto %>
      <div id="photos_div" style="margin-bottom:10px;">
        <%= f.fields_for :photos do |photos_form| %>
          <div id="wrapper_div<%=photos_form.index%>" class="wrapper_div">
            <%if @photograph.photos[photos_form.index].persisted?%>
              <%= photos_form.hidden_field :_destroy%>
            <% end %>
            <div id="photodiv<%=photos_form.index%>" class="weui-uploader__file" <%unless @photograph.photos[photos_form.index].persisted?%>style="display:none;"<%end%>>
              <%=link_to nil, href:"#", onclick:"delete_editing_photo(#{photos_form.index});" do %>
                <i class="weui-icon-cancel" style="margin-left: 50px;"></i>
              <% end %>
              <div style="margin-top:-25px;float:left;">
                <%=image_tag @photograph.photos[photos_form.index].photo.url, id:"photo#{photos_form.index}", width:"80", height:"80"%>
              </div>
            </div>
            <div id="uploaddiv<%=photos_form.index%>" class="weui-uploader__input-box" <% unless @photograph.photos.select{|p|p.photo.present?}.size == photos_form.index %> style="display:none;"<%end%>>
              <%= photos_form.file_field :photo, class:"weui-uploader__input", onchange:"preview_photo(this,#{photos_form.index})" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    </br></br></br></br>
    <div class="form-actions">
      <%= f.button :submit, "提交" %>
    </div>
  <% end %>
</div>

app/views/photographs/index.html.erb
<div> <h2 class="page-header">活动作品管理 </h2>
</div>
<div>
  <div class="">
    <%=form_tag search_activity_photographs_path(@activity), method:"get", class:"form-inline", role:"form" do%>
      <div class="form-group">
        <label for="name">作品名称</label>
        <%=text_field_tag "name", '', class:"form-control"%>
      </div>
      <div class="form-group">
        <%=submit_tag "查询",  class:"form-control"%>
      </div>
    <%end%>
  </div>
  <div style="padding-top:20px;">
    <%= render partial: "records" %>
  </div>
</div>

app/views/photographs/new.html.erb
<div id="cover" style="width:100%;">
  <%=image_tag "cover.jpg", style:"width:100%;" %>
</div>
<center>
  <div onclick="$('#photograph_photos_attributes_0_photo').click();" style="background-color:#F8B62D;color:#40220F;margin:15px 0;padding:10px 0;width:90%;text-align:center;">
    <h4>上传图片</h4>
  </div>

<div style="width:90%;">
  <%= form_for(@photograph, url: {:action=>"create"} ) do |f| %>
    <div class="weui-cell <%if @photograph.errors.include?(:photos)%>weui-cell_warn<%end%>">
      <div class="weui-cell__hd">
        <%= f.label :photo, class:"weui-label", style:"text-align:left;" %>
      </div>
    </div>
    <div class="weui-cell <%if @photograph.errors.include?(:photos)%>weui-cell_warn<%end%>">
      <div id="photos_div" class="weui-cell__bd">
        <%= f.fields_for :photos do |photos_form| %>
          <div id="wrapper_div<%=photos_form.index%>" class="wrapper_div">
            <div id="photodiv<%=photos_form.index%>" class="weui-uploader__file" style="display:none;">
              <%=link_to nil, href:"#", onclick:"delete_photo(#{photos_form.index});" do %>
                <i class="weui-icon-cancel" style="margin-left: 50px;"></i>
              <% end %>
              <div style="margin-top:-25px;float:left;">
                <%=image_tag "pic_160.png", id:"photo#{photos_form.index}", width:"80", height:"80"%>
              </div>
            </div>
            <div id="uploaddiv<%=photos_form.index%>" class="weui-uploader__input-box" <% if photos_form.index > 0 %> style="display:none;"<%end%>>
              <%= photos_form.file_field :photo, class:"weui-uploader__input", onchange:"preview_photo(this,#{photos_form.index})" %>
            </div>
          </div>
        <% end %>
        <%if @photograph.errors.include?(:photos)%>请至少上传一张图片，格式为jpg, jpeg, png或gif<%end%>
      </div>
    </div>
    <div class="weui-cells__tips" style="text-align:left;">温馨提示：</br>建议您上传未经社交软件压缩过的原图，否则可能读取不到照片的参数而造成不能成功上传。</div>

    <div class="weui-cells weui-cells_form">
      <div class="weui-cell <%if @photograph.errors.include?(:name)%>weui-cell_warn<%end%>">
        <div class="weui-cell__hd">
          <%= f.label :name, class:"weui-label", style:"text-align:left;" %>
        </div>
      </div>
      <div class="weui-cell <%if @photograph.errors.include?(:name)%>weui-cell_warn<%end%>">
        <div class="weui-cell__bd">
          <%name_ph = @photograph.errors.size > 0 ? @photograph.errors.messages[:name][0] : "限15字符"%>
          <%= f.text_field :name, class:"weui-input", placeholder: name_ph%>
        </div>
      </div>
      <div id="name_rest" class="weui-cells__tips" style="text-align:left;">（剩余15字符）</div>
      <div class="weui-cell <%if @photograph.errors.include?(:intro)%>weui-cell_warn<%end%>">
        <div class="weui-cell__hd">
          <%= f.label :intro, class:"weui-label", style:"text-align:left;" %>
        </div>
      </div>
      <div class="weui-cell <%if @photograph.errors.include?(:intro)%>weui-cell_warn<%end%>">
        <div class="weui-cell__bd">
          <%intro_ph = @photograph.errors.size > 0 ? @photograph.errors.messages[:intro][0] : "限60字符"%>
          <%= f.text_area :intro, class:"weui-textarea", placeholder:intro_ph, rows:"5" %>
        </div>
      </div>
      <div id="intro_rest" class="weui-cells__tips" style="text-align:left;">（剩余60字符）</div>
      <%= f.hidden_field :user_id %>
      <%= f.hidden_field :activity_id %>

      <div class="weui-btn-area">
        <%= f.submit "确定发布", class:"weui-btn weui-btn_primary" %>
      </div>
    </div>
  <% end %>
</div>
</center>

app/views/photographs/new.js.erb
<%if @activity.photographs.find_by_user_id(@current_wechat_user.id).present? %>
  alert("您已经参加过活动啦");
<%else%>

  custom_popup({
    title: "上传图片",
    text: <%== ( render :partial => 'new',:formats=>[:html] ).to_json %>,
    buttons: [{ text: "关闭", onClick: function(){ $.closeModal();} }]
  });
<%end%>

app/views/photographs/show.html.erb
<div>
  <table class="table table-striped">
    <tbody>
      <tr>
        <td>作品名称</td>
      </tr>
      <tr>
        <td><%= @photograph.name %></td>
      </tr>
      <tr>
        <td>作者</td>
      </tr>
      <tr>
        <td><%= @photograph.user.name %></td>
      </tr>
      <tr>
        <td>当前票数</td>
      </tr>
      <tr>
        <td>
          <%= @photograph.vote_numbers.to_i %></br>
          <%@photograph.votes.each{|vote|%>
            <%= vote.user.nickname %>&nbsp;&nbsp;
          <%}%>
        </td>
      </tr>
      <tr>
        <td>作品简介</td>
      </tr>
      <tr>
        <td><%= @photograph.intro %></td>
      </tr>
      <tr>
        <td>拉票宣言</td>
      </tr>
      <tr>
        <td><%=@photograph.manifesto %></td>
      </tr>
      <tr>
        <td>作品展示</td>
      </tr>
      <tr>
        <td>
          <% @photograph.photos.each do |photo|%>
            <p><%= image_tag photo.photo.url%></p>
          <%end%>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/photographs/user_edit.js.erb
custom_popup({
  title: "上传图片",
  text: <%== ( render :partial => 'new',:formats=>[:html] ).to_json %>,
  buttons: [{ text: "关闭", onClick: function(){ $.closeModal();} }]
});

app/views/photographs/user_update.js.erb
window.location.href = '<%=url_for("show/#{@photograph.id}")%>';

app/views/photographs/vote.js.erb
$("#votes<%=@photograph.id%>").html(<%=@photograph.vote_numbers%>);
<%coupon= ''#(@current_wechat_user.photographs.size == 0 && @current_wechat_user.votes.size ==1) ? "您获得了一张#{Card.first.name}，请到我的优惠券查看！" : ""%>
<% dialog_content = @vote.errors.empty? ? "投票成功！#{coupon}" : @vote.errors.messages[:user_id][0] %>
$(".weui-dialog__bd").html("<%=dialog_content%>")
$('#iosDialog2').fadeIn(200);