config/routes.rb
Rails.application.routes.draw do
  resource :wechat, only: [:show, :create] do
    collection do
      get :message_box
      get :direct_message_box
    end
  end

  root to: 'visitors#works'
  get '/index'=>'visitors#index'
  get '/admin'=>'users#index'
  get '/ranking'=>'visitors#ranking'
  get '/review'=>'visitors#review'
  get '/intro'=>'visitors#intro'
  get '/works'=>'visitors#works'
  get '/my_account'=>'visitors#my_account'
  get '/subscribe'=>'visitors#subscribe'
  get '/show/:id'=>'visitors#show'

  devise_for :users

  resources :users

  resources :shops
  resources :cards
  resources :activities do
    resources :photographs do
      collection do
        get :search
      end
      member do
        get :vote
        get :user_edit
        patch :user_update
      end
    end
    #resources :coupons do
    #  collection do
    #    get :search
    #  end
    #end
  end
  namespace :api do
    namespace :v1 do
      resource :wechat, only: [:show, :create]
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :shop
  validates :name, :origin, presence: true

  def assigned?
    User.where("card_status=1").first
  end

  def duration
    start_date.strftime("%Y.%m.%d")+"——"+end_date.strftime("%Y.%m.%d")
  end

  def outer_url
    url ? url : ""
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_card, only: [:edit, :update, :destroy]

  def index
    @cards = @shop.cards.order("created_at desc").paginate(:page => params[:page])
  end

  def new
    @card = @shop.cards.build
  end

  def create
    @card = @shop.cards.create(card_params)
    if @card.errors.empty?
      flash[:notice] = "优惠券添加成功"
      redirect_to cards_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @card.update(card_params)
    if @card.errors.empty?
      flash[:notice] = "优惠券修改成功"
      redirect_to cards_path
    else
      render :edit
    end
  end

  def destroy
    if @card.assigned?
      flash[:notice] = "优惠券已经使用，无法删除"
    else
      @card.destroy
    end
    redirect_to cards_path
  end

  private

  def card_params
    params.require(:card).permit(:name, :origin, :url, :start_date, :end_date)
  end

  def set_card
    @card = Card.find(params[:id])
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_records.html.erb
  <table class="table table-striped">
    <thead>
      <tr>
        <th>优惠券名称</th>
        <th>来源</th>
        <th>有效期</th>
        <th colspan="2"><%=link_to "添加", new_card_path %></th>
      </tr>
    </thead>

    <tbody>
      <% if @cards.empty? %>
        <tr>
          <td colspan="5">暂无优惠券</td>
        <tr>
      <% else %>
      <% @cards.each do |card| %>
        <tr>
          <td><%= card.name %></td>
          <td><%= card.origin %></td>
          <td><%= card.duration %></td>
          <td><%= link_to "编辑", edit_card_path(card) %></td>
          <td><%= link_to "删除", card_path(card), method: 'delete' %></td>
        </tr>
      <% end %>
    <% end %>

    </tbody>
  </table>

<%= will_paginate @cards if @cards.respond_to? :total_pages%>

app/views/cards/edit.html.erb
<div> <h2 class="page-header">编辑优惠券 </h2>
</div>
<div>
  <%=simple_form_for @card, url: {:action=>"update"} do |f|%>
    <%=f.input :name %>
    <%=f.input :origin%>
    <%=f.input :url%>
    <%=f.input :start_date, as: :date, start_year: Date.today.year,
                            end_year: Date.today.year + 10%>
    <%=f.input :end_date, as: :date, start_year: Date.today.year,
                            end_year: Date.today.year + 10%>
    <div class="form-actions">
      <%=f.button :submit, "提交"%>
    </div>
  <%end%>
</div>

app/views/cards/index.html.erb
<div> <h2 class="page-header">优惠券管理 </h2>
</div>
<div>
  <div style="padding-top:20px;">
    <%= render partial: "records" %>
  </div>
</div>

app/views/cards/new.html.erb
<div> <h2 class="page-header">添加优惠券 </h2>
</div>
<div>
  <%=simple_form_for @card, url: {:action=>"create"} do |f|%>
    <%=f.input :name %>
    <%=f.input :origin%>
    <%=f.input :url%>
    <%=f.input :start_date, as: :date, start_year: Date.today.year,
                            end_year: Date.today.year + 10, default: 1.day.from_now%>
    <%=f.input :end_date, as: :date, start_year: Date.today.year,
                            end_year: Date.today.year + 10, default: 1.month.from_now%>
    <div class="form-actions">
      <%=f.button :submit, "添加"%>
    </div>
  <%end%>
</div>