config/routes.rb
Rails.application.routes.draw do
  resource :wechat, only: [:show, :create] do
    collection do
      get :message_box
      get :direct_message_box
    end
  end

  root to: 'visitors#works'
  get '/index'=>'visitors#index'
  get '/admin'=>'users#index'
  get '/ranking'=>'visitors#ranking'
  get '/review'=>'visitors#review'
  get '/intro'=>'visitors#intro'
  get '/works'=>'visitors#works'
  get '/my_account'=>'visitors#my_account'
  get '/subscribe'=>'visitors#subscribe'
  get '/show/:id'=>'visitors#show'

  devise_for :users

  resources :users

  resources :shops
  resources :cards
  resources :activities do
    resources :photographs do
      collection do
        get :search
      end
      member do
        get :vote
        get :user_edit
        patch :user_update
      end
    end
    #resources :coupons do
    #  collection do
    #    get :search
    #  end
    #end
  end
  namespace :api do
    namespace :v1 do
      resource :wechat, only: [:show, :create]
    end
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to '微信会员', users_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to '编辑账户', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to '编辑企业信息', edit_shop_path(@shop), class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to '编辑活动信息', edit_activity_path(@activity), class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to '活动作品管理', activity_photographs_path(@activity), class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to '优惠券管理', cards_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to '退出', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to '登录', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to '注册', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler nav-link" style="color:white;" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;管理菜单
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <ul class="nav navbar-nav">
        <%#= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/_wechat_footer.html.erb
<% if params[:action] != "subscribe" %>
  <div class="weui-tabbar footer">
    <%=link_to "/index" do %>
      <div align="center" class="<%if params[:controller] == 'visitors' && params[:action] == 'index'%>footer_on home_on<%else%>footer_off home_off<%end%>">
        <div class="footer_text">首页</div>
      </div>
    <%end%>
    <%=link_to "/works" do %>
      <div align="center" class="<%if params[:controller] == 'visitors' &&  params[:action] == 'works'%>footer_on work_on<%else%>footer_off work_off<%end%>">
        <div class="footer_text">作品</div>
      </div>
    <%end%>
    <%=link_to new_activity_photograph_path(@activity), remote:true do %>
      <div align="center" class="<%if params[:controller] == 'photographs' &&  params[:action] == 'new'%>footer_on upload_on<%else%>footer_off upload_off<%end%>">
        <div class="footer_text">上传</div>
      </div>
    <%end%>
    <%=link_to "/review" do %>
      <div align="center" class="<%if params[:controller] == 'visitors' &&  params[:action] == 'review'%>footer_on back_on<%else%>footer_off back_off<%end%>">
        <div class="footer_text">追溯</div>
      </div>
    <%end%>
    <%=link_to "/my_account" do %>
      <div align="center" class="<%if params[:controller] == 'visitors' &&  params[:action] == 'my_account'%>footer_on account_on<%else%>footer_off account_off<%end%>">
        <div class="footer_text">我的</div>
      </div>
    <%end%>
  </div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "管理系统" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Wcpc" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/subscribe.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
    <title><%=@activity.name%></title>
    <%= stylesheet_link_tag 'weui-rails', media: 'all' %>
    <%= javascript_include_tag 'application' %>
</head>
<body ontouchstart>
  <div style="position:absolute;bottom:0;top:0;left:0;right:0;">
    <div class="weui-tab">
      <div class="weui-tab__panel">
        <%= yield %>
      </div>
      <div id="iosDialog2" class="js_dialog" style="opacity: 1; display:none;">
        <div class="weui-mask"></div>
        <div class="weui-dialog">
          <div class="weui-dialog__bd"></div>
          <div class="weui-dialog__ft">
            <a class="weui-dialog__btn weui-dialog__btn_primary" href="javascript:;">知道了</a>
          </div>
        </div>
      </div>
    </div>
    <div id="wcpc_popup" class="weui-popup__container">
      <div class="weui-popup__overlay"></div>
      <div class="weui-popup__modal">

      </div>
    </div>

  </div>
</body>
</html>

app/views/layouts/wechat.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
    <title><%=@activity.name%></title>
    <%= stylesheet_link_tag 'weui-rails', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <script src="http://res.wx.qq.com/open/js/jweixin-1.2.0.js"></script>
    <%= wechat_config_js debug: false, api: %w(hideMenuItems onMenuShareTimeline onMenuShareAppMessage onMenuShareQQ closeWindow) -%>
    <script type="application/javascript">
      window.share_config = {
           "share": {
              "imgUrl": "",//分享图，默认当相对路径处理，所以使用绝对路径的的话，“http://”协议前缀必须在。
              "desc" : "<%= @activity.intro.squish.gsub(/<\/?.*?>/,'')%>",//摘要,如果分享到朋友圈的话，不显示摘要。
              "title" : "快来看！<%=@current_wechat_user.nickname%>分享了一张宝贝吃饭最萌瞬间，邀您共同参与及分享助力。",//分享卡片标题
              "link": "<%=root_url%>",//window.location.href,分享出去后的链接，这里可以将链接设置为另一个页面。
              "success":function(){//分享成功后的回调函数
              },
              'cancel': function () {// 用户取消分享后执行的回调函数
              }
          }
      };
      window.share_config.share.imgUrl = <%== image_url('share.jpg').to_json%>;
     wx.ready(function() {
       //wx.hideOptionMenu();
       wx.onMenuShareTimeline(share_config.share);//分享到朋友圈
       wx.onMenuShareAppMessage(share_config.share);//分享给好友
       wx.onMenuShareQQ(share_config.share);//分享给手机QQ
     });
    </script>
</head>
<body ontouchstart>
  <%=text_field_tag "share_photo_url", ""%>
  <div style="position:absolute;bottom:0;top:0;left:0;right:0;">
    <div class="weui-tab">
      <div class="weui-tab__panel">
        <%= yield %>
      </div>
      <%= render 'layouts/wechat_footer' %>
      <div id="iosDialog2" class="js_dialog" style="opacity: 1; display:none;">
        <div class="weui-mask"></div>
        <div class="weui-dialog">
          <div class="weui-dialog__bd"></div>
          <div class="weui-dialog__ft">
            <a class="weui-dialog__btn weui-dialog__btn_primary" href="javascript:;">知道了</a>
          </div>
        </div>
      </div>
    </div>
    <div id="wcpc_popup" class="weui-popup__container">
      <div class="close-popup"><a> <i class="weui-icon-cancel"></i> </a></div>
      <div class="weui-popup__overlay"></div>
      <div class="weui-popup__modal">

      </div>
    </div>

  </div>
</body>
</html>